#!/usr/bin/env python3
"""HarmonyOS Sans SC 字体子集化工具 (精简版)"""
import os, glob, sys
from fontTools.ttLib import TTFont
from fontTools.subset import Subsetter, Options

PROJECT = os.path.dirname(os.path.abspath(__file__))
FONTS = os.path.join(PROJECT, "assets", "font")

def scan():
    chars = set()
    for pat in ["**/*.html", "**/*.js", "**/*.css"]:
        for fp in glob.glob(os.path.join(PROJECT, pat), recursive=True):
            if ".git" in fp or "node_modules" in fp:
                continue
            try:
                text = open(fp, encoding="utf-8").read()
                for ch in text:
                    cp = ord(ch)
                    if (0x3000 <= cp <= 0x303F or 0x3040 <= cp <= 0x30FF or
                        0x4E00 <= cp <= 0x9FFF or 0x3400 <= cp <= 0x4DBF or
                        0xF900 <= cp <= 0xFAFF or 0xFF00 <= cp <= 0xFFEF):
                        chars.add(ch)
            except (UnicodeDecodeError, OSError):
                continue
    return chars

def sub(src, dst, chars):
    font = TTFont(src)
    cmap = set()
    for t in font["cmap"].tables:
        cmap.update(t.cmap.keys())
    safe = {c for c in chars if ord(c) in cmap}
    if not safe:
        font.close()
        return 0
    opts = Options()
    opts.layout_features = ["*"]
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    opts.glyph_names = False
    s = Subsetter(options=opts)
    s.populate(text="".join(safe))
    s.subset(font)
    font.flavor = "woff2"
    font.save(dst)
    sz = os.path.getsize(dst)
    font.close()
    return sz

def main():
    print("扫描字符...", flush=True)
    chars = scan()
    print(f"找到 {len(chars)} 个 CJK/假名字符", flush=True)

    mapping = {
        "HarmonyOS_Sans_SC_Regular.ttf": [400, 500],
        "HarmonyOS_Sans_SC_Bold.ttf": [700],
    }

    total = 0
    orig_total = 0
    css = []

    for name, weights in mapping.items():
        src = os.path.join(FONTS, name)
        if not os.path.exists(src):
            continue
        orig = os.path.getsize(src)
        orig_total += orig
        print(f"\n处理 {name} ({orig/1024/1024:.2f} MB)...", flush=True)
        for w in weights:
            out = os.path.join(FONTS, f"HarmonyOS_SC_{w}.woff2")
            sz = sub(src, out, chars)
            print(f"  weight {w}: {sz/1024:.1f} KB", flush=True)
            total += sz
            css.append(
                f"@font-face {{\n"
                f"  font-family: 'HarmonyOS Sans';\n"
                f"  src: url('./HarmonyOS_SC_{w}.woff2') format('woff2');\n"
                f"  font-weight: {w};\n"
                f"  font-style: normal;\n"
                f"  font-display: swap;\n"
                f"}}"
            )

    css_path = os.path.join(FONTS, "_harmonyos_faces.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by subset-fonts.py */\n\n" + "\n\n".join(css) + "\n")

    print(f"\n原始: {orig_total/1024/1024:.2f} MB", flush=True)
    print(f"裁剪后: {total/1024:.1f} KB", flush=True)
    print(f"减少: {(1-total/orig_total)*100:.1f}%", flush=True)
    print(f"CSS 已保存到: {css_path}", flush=True)

if __name__ == "__main__":
    main()
